services:
  - type: web
    name: task-manager-api
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.3
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com,127.0.0.1,localhost
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com,http://127.0.0.1:8000,http://localhost:8000
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
